[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "termux-api-stc"
version = "2.1.0"
description = "Libreria de envoltorio Python de Termux:API y utilidades Termux relacionadas"
requires-python = ">=3.7"
license = { text = "MIT" }

[tool.setuptools]
packages = ["termux_api_stc"]
